# Generated by Django 4.2.6 on 2023-10-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
