# Generated by Django 4.2.6 on 2023-10-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_phone_num_contact_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='app_store',
            new_name='url_1',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='play_market',
            new_name='url_2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='telegram_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='web_url',
        ),
    ]
