# Generated by Django 4.2.6 on 2023-10-25 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_app_store_portfolio_url_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/service/icon/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetranslation',
            name='title',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourclient',
            name='image',
            field=models.ImageField(upload_to='media/clients/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='logo',
            field=models.ImageField(upload_to='media/portfolio/logo/'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(upload_to='media/portfolio/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(upload_to='media/service/img/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/team_members/'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='media/tools/'),
        ),
    ]
